### ISSUE TITLE
Mismatch of pvalues and its samples

### ISSUE THREAD

**Issue by c-mertes** [BennyStrobes/SPOT#2]
As recommended in the readme, one should use the input file (`{prefix}_perind_numers.counts.gz`) from leafcutter as is. This file only encodes the colnames (sample names) and the rownames (cluster ids) and has therefore no entry in the first cell. This is not true for the [example file](https://github.com/BennyStrobes/SPOT/blob/7b39a5fb86dfaab163cf799c3e1ea92ed51ba7a9/example_data/exon_exon_junction_file.txt#L1) given in this repo that has a colname for the rownames aka `chrom`. 

This will swap the pvalues of all samples with the sample n-1 and you finally will miss the p-values of the last sample in the matrix.

This is an uncompressed and unmodified example file from a leafcutter clustering.
[bugreport_input.counts.txt](https://github.com/BennyStrobes/SPOT/files/5017441/bugreport_input.counts.txt)

```
python3 ./spot.py -j bugreport_input.counts.txt -o bugreport
head -n1 bugreport_md.txt
head -n1 bugreport_input.counts.txt 
```

**Comment by c-mertes** [comment]
@BennyStrobes could you comment on this as we are not sure if we interpreted this correctly or not. Since this is crucial for interpreting the results, we would appreciate any help.

**Comment by BennyStrobes** [comment]
Hi @c-mertes : Sorry for any confusion. You are correct that my example input file and my code had previously worked under the assumption of a header element describing the rownames ('chrom' in the previous example file). You are also correct that that contradicts with default LeafCutter output (thanks for pointing this out!). I have just pushed changes to the SPOT code and the SPOT example data to correspond with standard LeafCutter output (ie no header element to describe the rownames). Let me know if you have any further questions. And thanks for bringing this to my attention!

**Comment by c-mertes** [comment]
hi @BennyStrobes, thanks for the changes. Yes this worked now for us. And i guess also more convenient for the end user.
